# Generated by Django 4.2.1 on 2023-05-22 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_comment_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='tag',
            new_name='tags',
        ),
    ]
